import "./globals.css";

import { faHeart } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col justify-between min-h-screen">
          {children}
        </div>
        <footer className="py-4 flex justify-center font-primary items-center">
          Template built with <FontAwesomeIcon icon={faHeart} className="w-5 text-red-600 mx-1" /> by{' '}
          <a
            href="https://twitter.com/deepwhitman"
            target="_blank"
            rel="noreferrer"
            className="text-palette-primary font-bold px-1"
          >
            Bilal Tahir
          </a>
        </footer>
      </body>
    </html>
  );
}
